name = "EulerianCert"
defaultTargets = ["EulerianCert"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "0272bbe1c093d038d7257ab15306abd58245f9ff"

[[lean_lib]]
name = "EulerianCert"
